### ISSUE TITLE
Speed Analyzer blocks replace_link_with_first_in_nav

### ISSUE THREAD

**Issue by patej** [a3020/speed_analyzer#8]
This add-on seems to block the "replace_link_with_first_in_nav" attribute from working, at least on Concrete5 8.4.2. The redirection had suddenly stopped working, but after disabling Speed Analyzer it started to work again.

**Comment by a3020** [comment]
Thanks for reporting. I'd probably recommend enabling Speed Analyzer only for debugging / testing purposes. If you leave it on, it'll keep generating reports on every page load (causing unnecessary overhead). 

It's good to know there's a potential conflict with the `replace_link_with_first_in_nav` attribute.

**Comment by patej** [comment]
Yeah I enabled only for a while, but on a production site to try to figure out some things, so the change in how site functioned caught me and some others by surprise. Don't know if you can do anything about it, but might be good to add it as an information somewhere. Thanks for a useful add-on, anyway!

**Comment by a3020** [comment]
I just tested this on an 841 instance and can't replicate the issue. Also, that attribute is meant to replace a link in the `autonav` block, it doesn't do redirection by itself. I don't see any indication to why this would cause issues to be honest.

**Comment by patej** [comment]
Sorry I failed to mention that I have the redirection defined for pages with this attribute if the page is visited manually, too, as explained here: https://documentation.concrete5.org/tutorials/redirect-link-first-child-pages so that's the thing that breaks, then, I guess..

**Comment by a3020** [comment]
I set up that custom event, went to the page directly, and got redirected while SA is enabled.
