### ISSUE TITLE
SQL ERROR: after update from 1.2.1 to 1.2.5

### ISSUE THREAD

**Issue by exa18** [a3020/speed_analyzer#9]
Concrete5 8.5.4 (started from 8.4.5 or 8.5.0)

```
An exception occurred while executing 'ALTER TABLE SpeedAnalyzerReportEvents CHANGE reportId reportId CHAR(36) DEFAULT NULL COMMENT '(DC2Type:guid)'':

SQLSTATE[HY000]: General error: 1832 Cannot change column 'reportId': used in a foreign key constraint 'FK_1B88CBECBB333E0D'
```

In this table I have same as above change and set NULL to yes.
So I do not now what is changing?
I assume change reportId to reportId trigger exception.

**Comment by a3020** [comment]
Hi @exa18, I don't have time to look into this, but I'd probably remove the add-on / tables, and then install it again.

**Comment by exa18** [comment]
yes, I did and it is OK. I think with this exception package is still work BUT I did noticed before update to 1.2.5 my logs stops about after update to version 8.5.0. I just put this as record.

Thank you.
